### DISCUSSION TITLE
How to get Burrito to stay on top of GW2 window?

### DISCUSSION THREAD

**Discussion by rupiperse** [AsherGlick/Burrito#359] [Q&A]
Seems like an awesome alternative to BlishHUD. Installs just fine and seems to work when on top of everything else. I'm using EndeavourOS with Plasma 6.

The only problem for me is that the burrito window is stuck behind the GW2 window. I'm running Burrito in verbose mode and this is the output I get. Says the burrito_link environment arg is invalid. So is it not launching correctly with ArcDPS?

```
Godot Engine v3.3.2.stable.official - https://godotengine.org
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
Failed loading custom cursor: X_cursor
Using GLES3 video driver
OpenGL ES 3.0 Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.57, 6.10.10-arch1-1)
OpenGL ES Batching: ON
        OPTIONS
        max_join_item_commands 16
        colored_vertex_format_threshold 0.25
        batch_buffer_size 16384
        light_scissor_area_threshold 1
        item_reordering_lookahead 4
        light_max_join_items 32
        single_rect_fallback False
        debug_flash False
        diagnose_frame False
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.usb-SteelSeries_Arctis_Pro_Wireless-00.stereo-game
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
JoypadLinux: udev enabled and loaded successfully.
 
CORE API HASH: 0
EDITOR API HASH: 0
Loading resource: res://default_env.tres
Loading resource: res://Settings.gdc
Loading resource: res://Spatial.tscn
Loading resource: res://Spatial.gdc
Loading resource: res://Spatial.gdns
Loading resource: res://libburrito.tres
Loading resource: res://tacoparser.gdns
Loading resource: res://shaders/range_indicators.shader
Loading resource: res://burrito.png
Loading resource: res://Route2D.tscn
Loading resource: res://icon_close.png
Loading resource: res://RangeDialog.gdc
Loading resource: res://icon_new_icon.png
Loading resource: res://icon_change_texture.png
Loading resource: res://icon_adjust_points.png
Loading resource: res://icon_new_path.png
Loading resource: res://icon_new_point.png
Loading resource: res://SettingsDialog.gdc
Loading resource: res://Route.tscn
Loading resource: res://Route.gdc
Loading resource: res://Route.tres
Loading resource: res://icon.png
Loading resource: res://Icon.tscn
Loading resource: res://Icon.gdc
Loading resource: res://Gizmo/PointEdit.tscn
Loading resource: res://Gizmo/PointEdit.gdc
Loading resource: res://Gizmo/YPlaneDragmove.gdc
Loading resource: res://Gizmo/PlaneDragmove.gdc
Loading resource: res://Gizmo/XZPlaneDragmove.gdc
Loading resource: res://Gizmo/arrow_mesh.tres
Loading resource: res://Gizmo/gizmo_base.tres
Invalid burrito_link environment arg: 

```

Thanks in advance to anybody willing to help.

**Comment by AsherGlick** [comment]
Window manager issues are the most common problem with burrito right now, so it is possible and likely that is what you are experiencing. 

---

Before we get into window managers though lets be sure burrito link is running properly because I dont think I see the connection occurring in your log.

The first thing I would recommend you do is make sure you download the version of burrito and burrito_link from the github page. I have been a little behind on updating the regular front-page but plan to do that soon as we will be merging xml_converter into master in short order and that will be a big update.

I would recommend using the `dll` version of burrito link instead of the `.exe` if that is what you are currently using. The `exe` requires you to specify all the wine environment variables needed to run it inside the same wine prefix as gw2, while the `dll` will automatically be launched inside the correct prefix without setting arguments.

If you are also using arcdps and that is taking the `d3d11.dll` spot then you can just rename the burrito link dll to something like `arcdps_burrito_link.dll` and put it in the same folder as arcdps to get arcdps to load it. Burrito link has specific entrypoints for arcdps.

---

Now for window mangers: Every one is a little bit different and we dont support all of them out of the box right now. The only one officially supported is GNOME on X11. However many other ones are supported by various community members.

Start by running the commands
```
inxi -Gxxx; wmctrl -m -v
```
This will give some background info on your graphics stack and window manager. From there you might be able to find other issues or discussions in this repo about those. IIRC plasma6 is kde plasma so that is what you will probably see.

If you are running wayland then burrito might still have some issues. I do plan to make sure we support wayland in the future but because it behaves differently to x11 it can cause some issues.

**Reply by rupiperse** [reply]
Well look at that! I got the latest 1.4 version and now it's working. Is it supposed to stay on top of ALL windows though, when alt + tabbing? I can get around it by just minimizing GW2, so it's not cuch a big deal.

```
Godot Engine v3.3.2.stable.official - https://godotengine.org
XInput: Refreshing devices.
XInput: No touch devices found.
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Only one GPU found, using default.
Failed loading custom cursor: X_cursor
Using GLES3 video driver
OpenGL ES 3.0 Renderer: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.57, 6.10.10-arch1-1)
OpenGL ES Batching: ON
        OPTIONS
        max_join_item_commands 16
        colored_vertex_format_threshold 0.25
        batch_buffer_size 16384
        light_scissor_area_threshold 1
        item_reordering_lookahead 4
        light_max_join_items 32
        single_rect_fallback False
        debug_flash False
        diagnose_frame False
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.usb-SteelSeries_Arctis_Pro_Wireless-00.stereo-game
PulseAudio: detected 2 channels
PulseAudio: audio buffer frames: 512 calculated latency: 11ms
JoypadLinux: udev enabled and loaded successfully.
 
CORE API HASH: 0
EDITOR API HASH: 0
Loading resource: res://default_env.tres
Loading resource: res://Settings.gdc
Loading resource: res://Spatial.tscn
Loading resource: res://Spatial.gdc
Loading resource: res://Spatial.gdns
Loading resource: res://libburrito.tres
Loading resource: res://tacoparser.gdns
Loading resource: res://shaders/range_indicators.shader
Loading resource: res://burrito.png
Loading resource: res://Route2D.tscn
Loading resource: res://icon_close.png
Loading resource: res://RangeDialog.gdc
Loading resource: res://icon_new_icon.png
Loading resource: res://icon_change_texture.png
Loading resource: res://icon_adjust_points.png
Loading resource: res://icon_new_path.png
Loading resource: res://icon_new_point.png
Loading resource: res://SettingsDialog.gdc
Loading resource: res://Route.tscn
Loading resource: res://Route.gdc
Loading resource: res://Route.tres
Loading resource: res://icon.png
Loading resource: res://Icon.tscn
Loading resource: res://Icon.gdc
Loading resource: res://Gizmo/PointEdit.tscn
Loading resource: res://Gizmo/PointEdit.gdc
Loading resource: res://Gizmo/YPlaneDragmove.gdc
Loading resource: res://Gizmo/PlaneDragmove.gdc
Loading resource: res://Gizmo/XZPlaneDragmove.gdc
Loading resource: res://Gizmo/arrow_mesh.tres
Loading resource: res://Gizmo/gizmo_base.tres
Invalid burrito_link environment arg: 
accepted peer: 127.0.0.1:37306
Setting transient for
Successfully set transient property!
New Map
Saving Old Map
Loading New Map
Loading Json file from path /home/miikka/.Burrito-GW2/Markers/tw_mc_coretyria.json
New Map
Saving Old Map
Loading New Map
```
Here's my **inxi -Gxxx; wmctrl -m -v** if that's relevant in any way.

```
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] vendor: Sapphire
    driver: amdgpu v: kernel arch: RDNA-2 pcie: speed: 16 GT/s lanes: 16 ports:
    active: DP-5 empty: DP-3, DP-4, HDMI-A-2, Writeback-1 bus-ID: 03:00.0
    chip-ID: 1002:73bf class-ID: 0300
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel arch: GCN-5 pcie: speed: 8 GT/s lanes: 16 ports:
    active: HDMI-A-1 empty: DP-1,DP-2 bus-ID: 09:00.0 chip-ID: 1002:1638
    class-ID: 0300 temp: 60.0 C
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 24.1.2
    compositor: kwin_x11 driver: X: loaded: amdgpu dri: radeonsi gpu: amdgpu
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3440x1440 s-dpi: 96 s-size: 910x381mm (35.83x15.00")
    s-diag: 987mm (38.84")
  Monitor-1: HDMI-A-0 res: 3440x1440 dpi: 107 size: 819x346mm (32.24x13.62")
    diag: 889mm (35") modes: N/A
  API: EGL v: 1.5 hw: drv: amd radeonsi platforms: device: 0 drv: radeonsi
    device: 1 drv: radeonsi device: 2 drv: swrast gbm: drv: kms_swrast
    surfaceless: drv: radeonsi x11: drv: radeonsi inactive: wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.3-arch1.1
    glx-v: 1.4 direct-render: yes renderer: AMD Radeon Graphics (radeonsi
    renoir LLVM 18.1.8 DRM 3.57 6.10.10-arch1-1) device-ID: 1002:1638
  API: Vulkan v: 1.3.295 layers: 8 surfaces: xcb,xlib device: 0
    type: discrete-gpu hw: amd driver: mesa radv device-ID: 1002:73bf device: 1
    type: integrated-gpu hw: amd driver: mesa radv device-ID: 1002:1638
```

Thanks for hinting about which version to use. I guess I had downloaded an old version from github. It was named Burrito.zip.
