### ISSUE TITLE
Compound Value XML Export

### ISSUE THREAD

**Issue by AsherGlick** [AsherGlick/Burrito#129]
Idea for CompoundValue and CustomCompoundValue
================================================================================
Instead of having an implicit "if the child is exported it is not going to be exported in the parent, as discussed offline, we just explicitly define how the parent export works as a combination of its children.

```yaml
xml_parent_export: "{arg1},{arg2},{arg3}"
xml_child_export: ["arg4", "arg5", "arg6"]
```

For CompoundValues this would be fully automated. For CustomCompoundValues this would be more bespoke, in that we could not automatically validate that the parent or child were being exported properly without parsing the c++ code, but it would setup the structure needed for the custom c++ code to write parent or child values, which is something.

Color
--------------------------------------------------------------------------------
```yaml
xml_parent_export: "{Red},{Green},{Blue}"
xml_children_export: ["Alpha"]
```

```xml
<POI Color="red,green,blue" Alpha="alpha" />
```

Position
--------------------------------------------------------------------------------
```yaml
xml_parent_export: ""
xml_children_export: ["XPos","YPos","ZPos"]
```

```xml
<POI XPos="xpos" YPos="ypos" ZPos="zpos" />
```

Position with QPos for 4 dimensional gaming
--------------------------------------------------------------------------------

```yaml
xml_parent_export: "{XPos},{YPoz},{ZPos}"
xml_children_export: ["QPos"]
```
```xml
<POI Position="xpos,ypos,zpos" QPos="qpos"
```

Euler Rotation
--------------------------------------------------------------------------------
```yaml
xml_parent_export: "{XRot},{YRot},{ZRot}"
xml_children_export: []
```

```xml
<Poi Rotation="xrot,yrot,zrot" />
```

<del>

Future Possibilities
================================================================================

A 3D Box with 3 dimentions (custom input output delimiters)
--------------------------------------------------------------------------------

```yaml
# something to know how to import compound values that are not comma delimited
xml_parent_import_patterns: [
    "{width}x{height}x{depth}",
    "{width},{height},{depth}"
]
xml_parent_export: "{width}x{height}x{depth}"
xml_children_export: []
```

A Datetime (partial compound values)
--------------------------------------------------------------------------------
```yaml
xml_parent_import_patterns: [
    "{hour}:{minute}:{second} {year}/{month}/{day}"
]

xml_parent_export: ""
xml_children_export: {
    "Date": "{year}/{month}/{day}"
    "Time": "{hour}:{minute}:{second}"
}
```

Even though this is really complicated and we might want to relegate it to a custom class, if we wanted to support this there would still need to be something that could define the input/output for compound custom classes

</del>

Lets ignore that for now and just require that the `xml_parent_export` to only contain tokens of the children separated by a single comma.

Validation
================================================================================
With this we can do some rudimentary validation that all of the children are being serialized properly to xml, while making it obvious how the serialization occurs from the documentation. Instead of the "not immediately obvious but clear once you know" solution of removing any specific children exports from the parent export.
