### ISSUE TITLE
Reset to default settings

### ISSUE THREAD

**Issue by Tyjex** [AsherGlick/Burrito#317]
Is there any way to reset the overlay window to default? I edited mine to fit my 3440x1440 screen but enterd the values in the box the wrong way around now it seems the Burrito I need to click to pull up the settings is way off my screen and unclickable.

Also where are the values stored? I tried to completely remove everything and set it back to default, redownload the entire release and set it up again but it seems to keep my broken settings.

**Comment by AsherGlick** [comment]
Can you share a screenshot of the broken setup. Also can you share the output of the commands `inxi -Gxxx; wmctrl -m -v` I want to track which graphics stack this bug happened in so that we can come up with a better way of handling this problem then "Please go edit your settings file".

The settings file can be found in `~/.local/share/godot/app_userdata/Burrito/settings.json`.

If someone is reading this issue in the future this path will probably change in an upcoming version of Burrito. Hopefully when it does we will include the new path in the docs.

**Comment by Tyjex** [comment]
I am on Fedora Silverblue 40. Both those commands do not work for me but XDG_CURRENT_DESKTOP = GNOME and XDG_SESSION_TYPE = wayland, on flatseal steam is enabled for both socket=x11 and socket=wayland but I don't know if that matters. 

I am installing Burrito like this: https://blog.xenokore.com/installing-arcdps-and-burrito-for-guildwars-2-on-linux-steam/
I don't even know if it will work yet but arc dps is working and picks up the BurritoLink extension. 

I deleted the old settings.json restarted Burrito and it popped up again. I have 3 monitors with different sizes and the problem seems to be that it always opens on my 24" monitor after I previously set it up on my 34" UW, so it ends up offscreen and unusable. Is there a way to make it always open on my main monitor or is the fault my weird setup.

**Comment by AsherGlick** [comment]
I also run with a triple monitor setup, but they are all the same size. One of the known issues in the readme is that burrito does not snap to the gw2 window. If you are using gnome then you should be able to hold super/windows and click and drag the burrito window on top of the gw2 window. This can be done easily by opening the burrito menu to create the red box outline, and then dragging anywhere in the red box.

To run those commands on fedora you may need to run 
```
sudo yum install wmctrl inxi
```

Any screenshots you can share of your issues, where burrito is opening vs where gw2 is open would be useful for future debugging and development.

**Comment by Tyjex** [comment]
Silverblue uses rpm-ostree and the base system is immutable but I installed the tools and got the output even though I'm not sure wmctrl output is as expected:

```
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2080 SUPER] vendor: Micro-Star MSI
    driver: nvidia v: 550.78 arch: Turing pcie: speed: 8 GT/s lanes: 16 ports:
    active: none off: DP-2,DP-3,HDMI-A-1 empty: DP-1,Unknown-1 bus-ID: 2d:00.0
    chip-ID: 10de:1e81 class-ID: 0300
  Display: server: X.Org v: 1.20.14 with: Xwayland v: 24.1.0
    compositor: gnome-shell v: 46.2 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa alternate: nv
    gpu: nvidia,nvidia-nvswitch display-ID: :1 screens: 1
  Screen-1: 0 s-res: 6000x2520 s-dpi: 96 s-size: 1588x667mm (62.52x26.26")
    s-diag: 1722mm (67.81")
  Monitor-1: DP-2 note: disabled pos: primary,bottom-l
    model: LG (GoldStar) 34GK950F serial: 209731 res: 3440x1440 dpi: 109
    size: 800x330mm (31.5x12.99") diag: 867mm (34.1") modes: max: 3440x1440
    min: 640x480
  Monitor-2: DP-3 mapped: DP-4 note: disabled pos: bottom-r
    model: Asus PB277 serial: 82835 res: 2560x1440 hz: 75 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (27") modes: max: 2560x1440
    min: 640x480
  Monitor-3: HDMI-A-1 mapped: HDMI-0 note: disabled pos: top-center
    model: Medion MD20435 serial: 16843009 res: 1920x1080 hz: 60 dpi: 94
    size: 521x293mm (20.51x11.54") diag: 598mm (23.5") modes: max: 1920x1080
    min: 640x480
  API: OpenGL v: 4.6.0 vendor: nvidia v: 550.78 glx-v: 1.4
    direct-render: yes renderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
envir_utf8: 1
Invalid type of WM_CLASS property.
Invalid type of WM_CLASS property.
Cannot get class of the window manager (WM_CLASS).
Invalid type of _NET_WM_PID property.
Cannot get pid of the window manager (_NET_WM_PID).
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF
```

For some reason it was working just now when I started it to take some screenshot, after installing the packages and restarting my system it didn't work anymore. 

Anyway, when it worked I had two problems first the control icon was on top of the black lion icon like so:
![Screenshot from 2024-06-15 03-11-39](https://github.com/AsherGlick/Burrito/assets/28201656/76cd80d2-b141-40c9-8d53-9cce178f87ab)
![Screenshot from 2024-06-15 03-11-52](https://github.com/AsherGlick/Burrito/assets/28201656/bf3b9646-f5cc-4f59-8df4-0dcb461efd19)

And this is the behavior I experience before and now again when opening Burrito:
![Screenshot-Full](https://github.com/AsherGlick/Burrito/assets/28201656/8960fc0e-6dbb-4165-92f8-1447ff80e751)
 
you can see the icon is off my screen to the left in the black. 


And the second problem, which I might just come back to later if/when I get it working, was that whenever I changed anything in the overlay and closed it I had to press my Windows/Super-key twice to tab out of the game and back in otherwise I couldn't move. I guess it just grabs my inputs - maybe alt + tab would have done the job as well, its likely no big deal either way.
