### ISSUE TITLE
Invisible/broken launch

### ISSUE THREAD

**Issue by pellemeijer** [AsherGlick/Burrito#355]
Running on PopOS, GW2 client running through steam. 
Using the dll for the link, trying to execute the Burrito script gives 
```
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 4080/PCIe/SSE2
OpenGL ES Batching: ON
 
ERROR: get_as_text: Condition "!f" is true. Returned: String()
   At: core/bind/core_bind.cpp:2126.
ERROR: parse: Error parsing JSON at line 0: 
   At: core/bind/core_bind.cpp:3292.
ERROR: parse: Error parsing JSON at line 0: 
   At: core/bind/core_bind.cpp:3292.
accepted peer: 127.0.0.1:51726
Setting transient for
Successfully set transient property!
New Map
Saving Old Map
Loading New Map
```

So the link seems to be functioning, updates when changing zones as well, but the overlay is either invisible or not launched correctly. There doesn't seem to be any button. 

Burrito screen comes into vision for a split sec when launching, and there is an application open on taskbar as well. which shows it should be displaying a mostly empty window with a button in the top left. 

According to xdotool the burrito window should also have the same size and be on the same screen as gw2.

**Comment by AsherGlick** [comment]
It is possible the icon might be hidden behind a task bar.
Can you run and share the output of the following commands:
```bash
inxi -Gxxx; wmctrl -m -v
```

**Comment by pellemeijer** [comment]
```
Graphics:
  Device-1: NVIDIA vendor: Micro-Star MSI driver: nvidia v: 555.58.02 pcie:
    speed: 16 GT/s lanes: 16 ports: active: none off: DP-4,HDMI-A-2
    empty: DP-5,DP-6 bus-ID: 01:00.0 chip-ID: 10de:2704 class-ID: 0300
  Device-2: AMD vendor: Gigabyte driver: amdgpu v: kernel pcie:
    speed: 16 GT/s lanes: 16 ports: active: none
    empty: DP-1, DP-2, DP-3, HDMI-A-1, Writeback-1 bus-ID: 15:00.0
    chip-ID: 1002:164e class-ID: 0300
  Device-3: Sunplus Innovation 2K Webcam type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 9-1.4:4 chip-ID: 1bcf:0215
    class-ID: 0102
  Display: x11 server: X.Org v: 1.21.1.4 compositor: gnome-shell v: 42.9
    driver: X: loaded: amdgpu,ati,nouveau
    unloaded: fbdev,modesetting,radeon,vesa failed: nvidia gpu: nvidia,amdgpu
    display-ID: :1 screens: 1
  Screen-1: 0 s-res: 5120x1440 s-dpi: 108 s-size: 1204x342mm (47.4x13.5")
    s-diag: 1252mm (49.3")
  Monitor-1: DP-0 pos: primary,top-right res: 2560x1440 hz: 144 dpi: 109
    size: 597x336mm (23.5x13.2") diag: 685mm (27")
  Monitor-2: HDMI-0 pos: bottom-l res: 2560x1080 hz: 60 dpi: 81
    size: 798x334mm (31.4x13.1") diag: 865mm (34.1")
  OpenGL: renderer: NVIDIA GeForce RTX 4080/PCIe/SSE2
    v: 4.6.0 NVIDIA 555.58.02 direct render: Yes
envir_utf8: 1
Invalid type of WM_CLASS property.
Invalid type of WM_CLASS property.
Cannot get class of the window manager (WM_CLASS).
Invalid type of _NET_WM_PID property.
Cannot get pid of the window manager (_NET_WM_PID).
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF
```

**Comment by shangri26199** [comment]
having the same issue, burrito started something invisible in my taskbar.
```
./burrito.x86_64 
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
OpenGL ES Batching: ON
 
ERROR: get_as_text: Condition "!f" is true. Returned: String()
   At: core/bind/core_bind.cpp:2126.
ERROR: parse: Error parsing JSON at line 0: 
   At: core/bind/core_bind.cpp:3292.
ERROR: parse: Error parsing JSON at line 0: 
   At: core/bind/core_bind.cpp:3292.
accepted peer: 127.0.0.1:35810
Setting transient for
Successfully set transient property!
New Map
Saving Old Map
Loading New Map
New Map
Saving Old Map
Loading New Map
```
output of ` inxi -Gxxx; wmctrl -m -v`
```
Graphics:
  Device-1: NVIDIA AD104 [GeForce RTX 4070 Ti] vendor: ZOTAC driver: nvidia
    v: 550.120 arch: Lovelace pcie: speed: 16 GT/s lanes: 16 ports: active: none
    off: DP-4, DP-5, DP-6, HDMI-A-2 empty: none bus-ID: 01:00.0
    chip-ID: 10de:2782 class-ID: 0300
  Device-2: AMD vendor: ASRock driver: amdgpu v: kernel pcie: speed: 16 GT/s
    lanes: 16 ports: active: none empty: DP-1, DP-2, DP-3, HDMI-A-1, Writeback-1
    bus-ID: 17:00.0 chip-ID: 1002:13c0 class-ID: 0300 temp: 37.0 C
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6
    compositor: kwin_x11 driver: X: loaded: nvidia gpu: nvidia,nvidia-nvswitch
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 6400x2340 s-dpi: 80 s-size: 2022x739mm (79.61x29.09")
    s-diag: 2153mm (84.76")
  Monitor-1: DP-1 pos: bottom-l res: 1920x1080 hz: 60 dpi: 82
    size: 598x336mm (23.54x13.23") diag: 686mm (27.01") modes: N/A
  Monitor-2: DP-3 pos: top-right res: 1920x1080 hz: 60 dpi: 82
    size: 598x336mm (23.54x13.23") diag: 686mm (27.01") modes: N/A
  Monitor-3: DP-4 pos: primary,middle-c res: 2560x1440 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (26.97") modes: N/A
  Monitor-4: HDMI-0 pos: bottom-r res: 1920x1080 hz: 60 dpi: 82
    size: 598x336mm (23.54x13.23") diag: 686mm (27.01") modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia drv: amd radeonsi platforms: device: 0
    drv: nvidia device: 2 drv: radeonsi device: 3 drv: swrast gbm: drv: nvidia
    surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.120
    glx-v: 1.4 direct-render: yes renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
  API: Vulkan v: 1.3.275 layers: 8 surfaces: xcb,xlib device: 0
    type: discrete-gpu driver: N/A device-ID: 10de:2782 device: 1
    type: integrated-gpu driver: N/A device-ID: 1002:13c0 device: 2 type: cpu
    driver: N/A device-ID: 10005:0000
envir_utf8: 1
Invalid type of WM_CLASS property.
Invalid type of WM_CLASS property.
Cannot get class of the window manager (WM_CLASS).
Invalid type of _NET_WM_PID property.
Cannot get pid of the window manager (_NET_WM_PID).
Invalid type of _NET_SHOWING_DESKTOP property.
Cannot get the _NET_SHOWING_DESKTOP property.
Name: KWin
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

**Comment by smooth-baking-powder** [comment]
Same Problem

```
lsb_release -a
No LSB modules are available.
Distributor ID: Tuxedo
Description:    TUXEDO OS
Release:        24.04
Codename:       noble
Gui: KDE Wayland
```


```
./burrito.x86_64 
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 4080 SUPER/PCIe/SSE2
OpenGL ES Batching: ON
 
ERROR: get_as_text: Condition "!f" is true. Returned: String()
   At: core/bind/core_bind.cpp:2126.
ERROR: parse: Error parsing JSON at line 0: 
   At: core/bind/core_bind.cpp:3292.
ERROR: parse: Error parsing JSON at line 0: 
   At: core/bind/core_bind.cpp:3292.
accepted peer: 127.0.0.1:38522
```


```
inxi -Gxxx; wmctrl -m -v
Graphics:
  Device-1: NVIDIA AD103 [GeForce RTX 4080 SUPER] vendor: Micro-Star MSI
    driver: nvidia v: 560.35.03 arch: Lovelace pcie: speed: 16 GT/s lanes: 16
    ports: active: none off: DP-3,HDMI-A-2 empty: DP-2,DP-4 bus-ID: 01:00.0
    chip-ID: 10de:2702 class-ID: 0300
  Device-2: AMD Raphael vendor: ASUSTeK driver: amdgpu v: kernel
    arch: RDNA-2 pcie: speed: 16 GT/s lanes: 16 ports: active: none
    empty: DP-1,HDMI-A-1,Writeback-1 bus-ID: 0e:00.0 chip-ID: 1002:164e
    class-ID: 0300 temp: 40.0 C
  Device-3: Logitech C922 Pro Stream Webcam driver: snd-usb-audio,uvcvideo
    type: USB rev: 2.0 speed: 480 Mb/s lanes: 1 bus-ID: 1-12.3.3:19
    chip-ID: 046d:085c class-ID: 0102 serial: 5950946F
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: X: loaded: amdgpu,nvidia
    unloaded: fbdev,modesetting,nouveau,vesa dri: radeonsi gpu: nvidia,amdgpu
    d-rect: 7040x2520 display-ID: 0
  Monitor-1: DP-3 pos: bottom-l res: 5120x1440 size: N/A modes: N/A
  Monitor-2: HDMI-A-2 pos: top-right res: 1920x1080 size: N/A modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia drv: amd radeonsi platforms: device: 0
    drv: nvidia device: 1 drv: radeonsi gbm: drv: radeonsi surfaceless:
    drv: nvidia wayland: drv: nvidia x11: drv: swrast
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 560.35.03
    glx-v: 1.4 direct-render: yes renderer: NVIDIA GeForce RTX 4080
    SUPER/PCIe/SSE2 display-ID: :1.0
  API: Vulkan v: 1.3.275 layers: 8 surfaces: xcb,xlib,wayland device: 0
    type: discrete-gpu driver: N/A device-ID: 10de:2702 device: 1
    type: integrated-gpu driver: N/A device-ID: 1002:164e device: 2 type: cpu
    driver: N/A device-ID: 10005:0000
envir_utf8: 1
Invalid type of WM_CLASS property.
Invalid type of WM_CLASS property.
Cannot get class of the window manager (WM_CLASS).
Invalid type of _NET_WM_PID property.
Cannot get pid of the window manager (_NET_WM_PID).
Invalid type of _NET_SHOWING_DESKTOP property.
Cannot get the _NET_SHOWING_DESKTOP property.
Name: KWin
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```
